// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cesay.QR.API.Data;

#nullable disable

namespace cesay.QR.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230717152115_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cesay.QR.API.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 17, 15, 21, 15, 109, DateTimeKind.Utc).AddTicks(1747),
                            Description = "Şehrimizin en seçkin lezzet duraklarından biridir. Misafirlerine eşsiz bir yemek deneyimi sunan bu restoran, zengin menüsü ve şık atmosferiyle dikkat çekmektedir. İster iş toplantılarına ister özel kutlamalara uygun olan mekânımızda, lezzetli yemeklerle unutulmaz anlar yaşayabilirsiniz.",
                            ImageUrl = "https://www.happygroup.com.tr/uploads/source/2022/06/happy-01.jpg",
                            Latitude = 38.381934700000002,
                            Longitude = 27.112280500000001,
                            Name = "Munq",
                            Rate = 4.4000000000000004,
                            UpdatedDate = new DateTime(2023, 7, 17, 15, 21, 15, 109, DateTimeKind.Utc).AddTicks(1748)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 17, 15, 21, 15, 109, DateTimeKind.Utc).AddTicks(1750),
                            Description = "Yemekseverlerin uğrak noktası haline gelen bir mekândır. Eşsiz lezzetler sunan bu restoran, sıcak ve samimi atmosferiyle de kendinizi evinizde hissetmenizi sağlar. En sevdiğiniz yemekleri tatmak ve yeni tatlar keşfetmek için Restoran 2'yi tercih edebilirsiniz.",
                            ImageUrl = "https://www.happygroup.com.tr/uploads/source/2022/06/happy-01.jpg",
                            Latitude = 38.381934700000002,
                            Longitude = 27.112280500000001,
                            Name = "Last Point",
                            Rate = 4.5,
                            UpdatedDate = new DateTime(2023, 7, 17, 15, 21, 15, 109, DateTimeKind.Utc).AddTicks(1750)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 17, 15, 21, 15, 109, DateTimeKind.Utc).AddTicks(1752),
                            Description = "Eşsiz manzarası ve lezzetli yemekleriyle göz dolduran bir mekândır. Şehrin kalbinde bulunan bu restoran, ferah ve modern tasarımıyla dikkat çeker. Yüksek tavanları, geniş pencereleri ve rahat oturma alanlarıyla misafirlerine rahat ve huzurlu bir ortam sunar.",
                            ImageUrl = "https://www.happygroup.com.tr/uploads/source/2022/06/happy-01.jpg",
                            Latitude = 38.381934700000002,
                            Longitude = 27.112280500000001,
                            Name = "Kahve Diyarı",
                            Rate = 4.5999999999999996,
                            UpdatedDate = new DateTime(2023, 7, 17, 15, 21, 15, 109, DateTimeKind.Utc).AddTicks(1752)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
